export type DIPMethodName =
  | "grayscale"
  | "HSV"
  | "HLS"
  | "logarithmic"
  | "exponential"
  | "sqrt"
  | "sine"
  | "cosine"
  | "tangent"
  | "contrast_stretch"
  | "hist_eq"
  | "gamma"
  | "gaussian_blur"
  | "clahe"
  | "sharpen"
  | "segment"
  | "multisegment"
  | "adaptive_thresh"
  | "binary"
  | "open"
  | "dilate"
  | "erode"
  | "morphgradient"
  | "canny"
  | "sobel"
  | "niblack"
  | "sauvola"
  | "HOG"
  | "add"
  | "subtract"
  | "multiply"
  | "divide"
  | "LIPadd"
  | "LIPsubtract"
  | "LIPmultiply"
  | "LIPdivide"
  | "LIPscaleMult"
  | "NLE"
  | "DHVT"
  | "LOGReduction"
  | "LIPBiHistEq";

export interface DIPParams {
  gamma?: number;
  thresh?: number;
  threshold1?: number;
  threshold2?: number;
  k?: number;
  window_size?: number;
  kernel_size?: number;
  const?: number;
  M?:number;
  enhance?: number;
  amp?: number;
  NLEAlpha?: number;
  NLEBeta?: number;
  dhvtPlane?: number;
  logralpha?: number;
  logrbeta?: number;
  logrlam?: number;
}
